FROM golang:tip-alpine3.22 AS builder

WORKDIR /app

COPY . ./

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]